### ISSUE TITLE
provide some sane css defaults

### ISSUE THREAD

**Issue by kdoh** [kdoh/begin#18]
some general commonalities for most of my prototypes:

``` css
* { box-sizing: border-box; }
html, body { height: 100%; }

body {
  margin: 0;
}
```
